spring:
  application:
    name: ms-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
          - classpath:/config/

server:
  port: 8021

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8020/eureka/