server:
  port: 8021
  ssl:
    enabled: true
    key-store: file:${KEYSTORE_LOCATION}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-password: ${KEYSTORE_PASSWORD}
    trust-store: file:${TRUSTSTORE_LOCATION}
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12
    client-auth: need


spring:
  application:
    name: ms-config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${GITHUB_CONFIGURATIONS_URL}
          username: ${GITHUB_USER}
          password: ${GITHUB_TOKEN}



management:
  server:
    port: 9021
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health, refresh
  endpoint:
    health:
      show-details: never

info:
  app:
    name: ms-config-server
    description: Microservicio de Configuraciones
  env:
    enabled: true


eureka:
  instance:
    prefer-ip-address: false
    hostname: ms-config-server
  client:
    tls:
      enabled: true
      key-store: file:${KEYSTORE_LOCATION}
      key-store-type: PKCS12
      key-store-password: ${KEYSTORE_PASSWORD}
      key-password: ${KEYSTORE_PASSWORD}
      trust-store: file:${TRUSTSTORE_LOCATION}
      trust-store-type: PKCS12
      trust-store-password: ${TRUSTSTORE_PASSWORD}
    serviceUrl:
      defaultZone: https://ms-registry-server:8020/eureka/