server:
  port: 8022
  ssl:
    enabled: true
    key-store: file:${KEYSTORE_LOCATION}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-password: ${KEYSTORE_PASSWORD}
    trust-store: file:${TRUSTSTORE_LOCATION}
    trust-store-password: ${TRUSTSTORE_PASSWORD}
    trust-store-type: PKCS12
    client-auth: none

management:
  server:
    port: 9022
    ssl:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

eureka:
  instance:
    prefer-ip-address: false
    hostname: ms-api-gateway
  client:
    tls:
      enabled: true
      key-store: file:${KEYSTORE_LOCATION}
      key-store-type: PKCS12
      key-store-password: ${KEYSTORE_PASSWORD}
      key-password: ${KEYSTORE_PASSWORD}
      trust-store: file:${TRUSTSTORE_LOCATION}
      trust-store-type: PKCS12
      trust-store-password: ${TRUSTSTORE_PASSWORD}
    serviceUrl:
      defaultZone: https://ms-registry-server:8020/eureka/

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

resilience4j:
  circuitBreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60s
        permitted-number-of-calls-in-half-open-state: 3
  timelimiter:
    configs:
      default:
        timeout-duration: 3s
    


spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-auth-auth
              uri: lb://MS-AUTH
              predicates:
                - Path=/api/auth/**
                - Method=POST
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-auth-auth

            - id: ms-auth-vendor
              uri: lb://MS-AUTH
              predicates:
                - Path=/api/vendors/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-auth-vendor
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: []
                    statuses: [SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 60ms
                      factor: 2
                      basedOnPreviousValue: false
                
            - id: ms-auth-role
              uri: lb://MS-AUTH
              predicates:
                - Path=/api/roles/**
                - Method=GET
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-auth-role
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: []
                    statuses: [SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 60ms
                      factor: 2
                      basedOnPreviousValue: false

            - id: ms-products
              uri: lb://MS-PRODUCTS
              predicates:
                - Path=/api/products/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-products
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: []
                    statuses: [SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 60ms
                      factor: 2
                      basedOnPreviousValue: false

            - id: ms-clients
              uri: lb://MS-CLIENTS
              predicates:
                - Path=/api/clients/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-clients
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: []
                    statuses: [SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 60ms
                      factor: 2
                      basedOnPreviousValue: false

            - id: ms-sales
              uri: lb://MS-SALES
              predicates:
                - Path=/api/sales/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: cb-ms-sales
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: []
                    statuses: [SERVICE_UNAVAILABLE, GATEWAY_TIMEOUT]
                    backoff:
                      firstBackoff: 10ms
                      maxBackoff: 60ms
                      factor: 2
                      basedOnPreviousValue: false