## Nombre de la App
spring.application.name=sales_api


## Configuracion de la DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.open-in-view=false

#OAuth2 (Configuración para ser utilizada con par de claves RSA)
spring.security.oauth2.resourceserver.jwt.public-key-location=${JWT_PUBLIC_KEY_LOCATION}
spring.security.oauth2.resourceserver.jwt.private-key-location=${JWT_PRIVATE_KEY_LOCATION}

#cors Allowed Origins
app.security.cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

#urls publicas
app.security.public-urls=/api/auth/login,/api/auth/refresh

#configuracion cookie Same site
app.security.cookie.same-site=None

## Access token(900 segundos = 15 minutos) y Refresh token(604800 segundos = 7 días)
app.security.jwt.refresh-token-expiration-seconds=604800
app.security.jwt.access-token-expiration-seconds=900